### ISSUE TITLE
There may be multiple resources for a specific vendor

### ISSUE THREAD

**Issue by RenaudWasTaken** [cncf-tags/container-device-interface#10]
Hello!

I'm opening this issue following Adrian's comment on https://github.com/container-orchestrated-devices/container-device-interface/pull/2

> /etc/cdi/vendor.json
> 
> This hints that there would be one file per vendor (or per vendor, runtime)
> in my opinion thats really more of a "vendor resource" file.
> 
> There may be multiple files for a specific vendor.
> the hardware may be the same but with different configurations.
> 
> e.g for networking device, a containerSpec would differ whether or not enabling RDMA is desired.
> 
> another example is differentiating between network resources because they are simply wired differently (connected to different physical networks).
> 
> so in that case we would have (for all runtimes):
> 
> /etc/cdi/vendor-rdma-resource-net-a.json
> /etc/cdi/vendor-rdma-resource-net-b.json
> /etc/cdi/vendor-resource-net-c.json

This seemed an important enough thought to open an issue about. There's a very tactical question which is should we rename the occurrence `/etc/cdi/vendor.json` to `/etc/cdi/resource.json` (I think yes).

I'd also be interested in getting more details about a real world example of the scenario you pointed out, @adrianchiris what would the CDI file look like? Are they different resources (rather than devices) because they need widely different operations or is this a way to pass down information/parameters to a hook?

Thanks!

**Comment by adrianchiris** [comment]
An RDMA enabled NIC would have the following devices: 
```
 "Devices": [
                {
                    "PathOnHost": "/dev/infiniband/ucm0",
                    "PathInContainer": "/dev/infiniband/ucm0",
                    "CgroupPermissions": "rwm"
                },
                {
                    "PathOnHost": "/dev/infiniband/issm0",
                    "PathInContainer": "/dev/infiniband/issm0",
                    "CgroupPermissions": "rwm"
                },
                {
                    "PathOnHost": "/dev/infiniband/umad0",
                    "PathInContainer": "/dev/infiniband/umad0",
                    "CgroupPermissions": "rwm"
                },
                {
                    "PathOnHost": "/dev/infiniband/uverbs0",
                    "PathInContainer": "/dev/infiniband/uverbs0",
                    "CgroupPermissions": "rwm"
                },
                {
                    "PathOnHost": "/dev/infiniband/rdma_cm",
                    "PathInContainer": "/dev/infiniband/rdma_cm",
                    "CgroupPermissions": "rwm"
                }
            ],
```

A non RDMA enabled NIC would have:
```
 "Devices": []
```
for example SR-IOV VF of a network card, where today only the ID of the device matters as its passed down to CNIs.

Now, Each can be wired to a different network.
We would then have the following `kinds` all technically originating from the same vendor e.g:

- networkingVendor.com/sriov-net-1
- networkingVendor.com/sriov-net-1-rdma
- networkingVendor.com/sriov-net-2
- networkingVendor.com/sriov-net-2-rdma

Some off-topic question heres: 
Would it be possible to inject env variables into container using CDI ?
Should there be a way to correlate within the container between a device and its resources ?
(when multiple resources are passed to the container)
