### ISSUE TITLE
CNI and CDI integration

### ISSUE THREAD

**Issue by squeed** [cncf-tags/container-device-interface#104]
Greetings from the CNI project.

One of the annoying sticking points of the CNI spec is that there isn't a good way for networks to interact with hardware, especially when something needs to be allocated on a per-attachment (i.e. per-container-nic) basis. We have an [issue](https://github.com/containernetworking/cni/issues/891) for this without any real progress.

There are really two separate problems here:

1. CNI networks should be able to say that they need a specific hardware resource
2. CNI plugins need to know which resource was allocated for them by some external process

So, I've opened this, well, open-ended issue in an attempt to build some bridges and do some brainstorming.

Thoughts? Does the CDI have some kind of "result" type that would be neatly embedded in a CNI ADD request?

**Comment by elezar** [comment]
@kad  as discussed in the meeting. Please take a look at this.
