### ISSUE TITLE
GetRegistry should not reconfigure registry on every call

### ISSUE THREAD

**Issue by elezar** [cncf-tags/container-device-interface#132]
See https://github.com/moby/moby/pull/45134#discussion_r1143972281 and https://github.com/moby/moby/pull/45134#discussion_r1143987357

**Comment by elezar** [comment]
@klihub I think this has been addressed by your most recent refactoring changes from https://github.com/cncf-tags/container-device-interface/pull/192

**Comment by klihub** [comment]
> @klihub I think this has been addressed by your most recent refactoring changes from #192
> 
> Please close this if this is the case.

With those changes in place, GetRegistry() is now a GetDefaultCache() + and optional call to Cache.Configure() on the default cache instance. It only ends up calling Configure() if there are options passed to it. It is not smart about the options themselves, though. If you call it twice in a row with the same options, it will call Configure() both times. But this should be good enough to address the main complains in the above linked moby PRs. So closing this.
