### ISSUE TITLE
Add CDI support to ctr command line

### ISSUE THREAD

**Issue by elezar** [cncf-tags/container-device-interface#142]
Support for specifying CDI devices should be added to the `ctr` command line. This should mirror what is done for `podman` and `docker`.

Note that `ctr` supports a `--gpu` flag for requesting NVIDIA GPUs and this feature should be considered a replacement for this.

**Comment by elezar** [comment]
I created https://github.com/containerd/containerd/pull/8525 to add support using the existing CDI infrastructure instead.

**Comment by bart0sh** [comment]
> I created [containerd/containerd#8525](https://github.com/containerd/containerd/pull/8525) to add support using the existing CDI infrastructure instead.

Can you explain where CDI injection happens? Is it only on a client(ctr) side, or it also involves containerd somehow?

**Comment by elezar** [comment]
@bart0sh this only happens on the client (ctr) side.
