### ISSUE TITLE
Why is the devices.annotations field in the SPEC not being used?

### ISSUE THREAD

**Issue by Apokleos** [cncf-tags/container-device-interface#152]
Hi, @elezar 
For the CDI, I want to confirm that why the field `devices.annotations` in the SPEC is not being used? 
And there's no further explanation about it.

Thx.

**Comment by zvonkok** [comment]
Annotations are meta-information for other entities e.g. for the Kata runtime to deduce specific information that is not part of the device specification but related to Kata. 
It's consumed by other entities that leverage CDI.

**Comment by Apokleos** [comment]
> Annotations are meta-information for other entities e.g. for the Kata runtime to deduce specific information that is not part of the device specification but related to Kata. It's consumed by other entities that leverage CDI.
> 
Thx @zvonkok.

The `devices.annotation`, I mean,  is  in `Device {.. Annotations map[string]string..}`.
The result as I test with containerd/cdi/kata, no annotations will be passed to kata runtime.
And I have deep dive into the code of cdi and found that the annotations are not parsed in [InjectDevices](https://github.com/container-orchestrated-devices/container-device-interface/blob/9c63527894228d1eb48e693b62042a422e0a6558/pkg/cdi/cache.go#L217)

**Comment by elezar** [comment]
There is no mapping from CDI annotations to mofications to the OCI Runtime specifications at a spec level. The annotations are there for specific CDI consumers -- such as Kata -- to make additional decisions when updating the OCI Runtime specifications but should not affect the spec modifications in general.

@zvonkok may be able to provide a more concrete example of where these are used in Kata specifically.

**Comment by Apokleos** [comment]
> 
> There is no mapping from CDI annotations to mofications to the OCI Runtime specifications at a spec level. 
The annotations are there for specific CDI consumers -- such as Kata -- to make additional decisions when updating the OCI Runtime specifications but should not affect the spec modifications in general.
>
> @zvonkok may be able to provide a more concrete example of where these are used in Kata specifically.
>
OK, Thx.
 I‘m looking forward to learn examples provided by @zvonkok

**Comment by Apokleos** [comment]
> Annotations are meta-information for other entities e.g. for the Kata runtime to deduce specific information that is not part of the device specification but related to Kata. It's consumed by other entities that leverage CDI.
>
Hi @zvonkok , I would like to learn more about CDI device.annotations in the case of Kata. 
In the [example](https://github.com/kata-containers/kata-containers/pull/4699#issuecomment-1204982034) you provided, there are annotations set, but I am not clear how they are used and how they are passed to the VMM. 
In addition, through the code that supports CDI in Kata, I found that device.annotations cannot be passed through the entire create container process. I hope I didn't misunderstand this part of the code.

Cloud you please help me clarify this？ 
Thx.
