### ISSUE TITLE
Add support for hotpluggable devices

### ISSUE THREAD

**Issue by byako** [cncf-tags/container-device-interface#154]
Current CDI spec format only allows fixed list of devices to be defined. It seems to be possible in OCI spec to allow a container access to the devices that were also  plugged in after the container was created: https://github.com/opencontainers/runtime-spec/blob/main/config-linux.md#allowed-device-list .

It would be nice to have similar mechanism in CDI, that would allow, for instance, usage of dynamically created SR-IOV virtual devices without needing to regenerate CDI spec and restart the container. One example workload for such a mechanism is monitoring software that need to access all available devices of particular major type.

**Comment by zvonkok** [comment]
`UpdateContainerResources` only updates cgroup resources and only CPU + memory (https://github.com/sjenning/kubernetes/blob/b032f6e1cbd30d7c97628e7241b60b69f702babc/pkg/kubelet/apis/cri/services.go#L47) (https://kubernetes.io/docs/tasks/configure-pod-container/resize-container-resources/) AFAIK you cannot update a containers allocation of an extended resource which I suppose would be the way of exposing a VF (SRIOV Device Plugin).

**Comment by zvonkok** [comment]
Exposing a VF in a container means mounting the corresponding `/dev/vfio/<num>` to the container's rootfs. I am unsure how this can be done vendor agnostic if DevicePlugins are not used.

**Comment by byako** [comment]
Updating CDI spec can be done easily indeed. The problem is however: how to add and remove devices from a running container without restarting it and without running it in privileged mode.

Device Plugins have nothing to do with this, neither has extended resources. The problem we're facing is related to Dynamic Resource Allocation resource drivers Our resource driver generates CDI entries for SRIOV VFs as they are being provisioned and removes entries before the VFs are unprovisioned in HW. Meanwhile monitoring software running in a Pod in K8s cluster has to have access to all devices even SRIOV VFs that could appear on host after the monitoring software Pod has been started. At the moment the only two ways to have access to dynamically appearing and disappearing VFs are :
- have monitoring software running in privileged Pod bypassing DRA resource driver so that _all_ host devices are accessible to such Pod
- have some sort of additional action from DRA resource driver that would restart or redeploy monitoring software Pod to pick up fresh list of devices. This is of course terrible, very expensive and potentially dangerous.

**Comment by zvonkok** [comment]
Well, they have because Device Plugins can leverage CDI as well, and you have not pointed out that you're using DRA. 

The problem is that the CRI does not provide an interface to update a CDI device after the `CreateContainer` CRI call. 

Who creates the VFs? How does your DRA plugin know that there are new VFs? How do you inform the monitoring Pod that there are new VFs as CDI devices, are you updating the Pod spec and adding a new resourceClaim?

**Comment by zvonkok** [comment]
Ideally some entity creates a VF, a webhook monitors the PCIe space and updates the resourceClaim on the monitoring Pod and the CRI does the update in the correct way....

**Comment by byako** [comment]
There is no need to update the resource claim.

> Who creates the VFs? How does your DRA plugin know that there are new VFs? How do you inform the monitoring Pod that there are new VFs as CDI devices, are you updating the Pod spec and adding a new resourceClaim?

kubelet-plugin of our DRA resource driver is the one who changes amount of VFs on host. We don't update the monitoring Pod at the moment, this is all alpha / beta software so for current release of our driver we'll just run it in privileged mode hoping for an alternative in future, hence this issue.

Currently the situation is this: 
- there is one resource claim for monitoring class, it has one device with several device nodes that are actual physical PCI devices; 
- other resource claims come and go and they can change the amount of actual PCI devices on host

If we had to go with signaling, in theory, when the amount of VFs is being changed by kubelet-plugin - it would also update the CDI device for monitoring claim / Pod with new or (without gone) VF deviceNodes entries. Subsequent triggering of restarting / redeploying of monitoring Pod would make runtime read updated CDI spec. But killing the monitoring Pod every time VFs are added / gone is least appealing of possibilities.

> Ideally some entity creates a VF, a webhook/DRA resource driver monitors the PCIe space and updates the resourceClaim on the monitoring Pod and the CRI does the update in the correct way....

DRA resource drivers cannot arbitrary fiddle with the resource claims, especially after they were allocated and taken into use, unless I'm terribly mistaken. Claim points to CDI device, we change the CDI device's amount of deviceNodes it is much less intrusive into Kubernetes internals than dealing with such high level objects as ResourceClaims IMHO.
