### ISSUE TITLE
GitHub repo name

### ISSUE THREAD

**Issue by pohly** [cncf-tags/container-device-interface#156]
This repo used to be at github.com/container-orchestrated-devices/container-device-interface, which is also the module path according to go.mod.

But that repo now gets redirected to https://github.com/cncf-tags/container-device-interface. I suppose Go can handle that, but it's a bit confusing. Perhaps add an explanation in the main README?

**Comment by kad** [comment]
Right now github is serving the redirect to new location, so any older code that imports it via old name should continue to work. For future, we would need to update all users to new name, together with renaming in the go.mod.
There are discussions about to get shorter URL `tags.cncf.io` to be redirect to `github.com/cncf-tags/` (similar to `sigs.k8s.io`), but that is not decided yet, thus a bit of delay on our side to update go.mod.

**Comment by elezar** [comment]
This is dependent on https://github.com/cncf/toc/issues/1152 where we have requested the URLs.
