### ISSUE TITLE
Links in note are incorrect

### ISSUE THREAD

**Issue by CsatariGergely** [cncf-tags/container-device-interface#157]
The note in the README file refers to `github.com/container-orchestrated-devices/container-device-interface/pkg/cdi` while the correct reference is `https://github.com/cncf-tags/container-device-interface/tree/main/pkg/cdi`.

**Comment by elezar** [comment]
@CsatariGergely thanks for calling this out. We recently migrated our repos and the docs still refer to the old address. Would you be up to creating a PR that addresses the inconsistencies?

**Comment by ATREAY** [comment]
hey @elezar, can I work on this issue?

**Comment by elezar** [comment]
@ATREAY you're welcome to submit a PR. 

We were going to wait on a "vanity URL" for this `cncf-tags` repos, but this does not have to be a blocker. (see https://github.com/cncf/toc/issues/1152).

**Comment by ATREAY** [comment]
Hey @elezar, I've made the necessary changes. Please take a look when you get a chance.

**Comment by elezar** [comment]
As far as I understand this has been addressed. Closing this issue. Please reopen if the links are still invalid.
