### ISSUE TITLE
Add notion of vendor "owned" directories to the CDI spec

### ISSUE THREAD

**Issue by klueska** [cncf-tags/container-device-interface#16]
In order to operate correctly in certain environments, containers running with NVIDIA GPUs require selective injection of files under `/proc/driver/nvidia` rather than having the entire tree injected in.

As such, it would be great if the CDI spec included a way to specify a list of directories "owned" by a vendor that the runtime will disallow users from trying to mount in. It should also prevent the runtime itself mounting anything in over these directories. Vendor specific hooks will then be free to work within these directories as they see fit.

In this case of the example above. The `nvidia.com` vendor would take ownership of the `/proc/driver/nvidia` directory.

**NOTE:** This requires a change to the spec, but I don't yet have a good proposal for how to add it 

/cc @RenaudWasTaken @mrunalp @bart0sh @kad @adrianchiris

**Comment by elezar** [comment]
The OCI spec allows for a list of [`MaskedPaths` to be specified](https://github.com/opencontainers/runtime-spec/blob/1c3f411f041711bbeecf35ff7e93461ea6789220/specs-go/config.go#L175). In the case of the proc paths, one may be able to mask the root (e.g. `/proc/driver/nvidia`) and then specify any sub-directories as [`ReadonlyPaths`](https://github.com/opencontainers/runtime-spec/blob/1c3f411f041711bbeecf35ff7e93461ea6789220/specs-go/config.go#L177).
