### ISSUE TITLE
Tag v0.6.1

### ISSUE THREAD

**Issue by elezar** [cncf-tags/container-device-interface#160]
We should tag `v0.6.1` including the changes to remove the `runc` dependency.

* https://github.com/cncf-tags/container-device-interface/pull/158

**Comment by klihub** [comment]
I'm fine with tagging a new version.

**Comment by bart0sh** [comment]
no objections

**Comment by elezar** [comment]
Release is out https://github.com/cncf-tags/container-device-interface/releases/tag/v0.6.1
