### ISSUE TITLE
vendor.json file system path  

### ISSUE THREAD

**Issue by zvonkok** [cncf-tags/container-device-interface#18]
Currently container engines can read hook description files from different locations, /etc, /usr, /run and I think we should define also for the CDI vendor.json file possible path were such a file would be saved. 

On OS's that have read-only file-systems not every location is writable. 

With the prestart hooks we had the issue that if the prestart hook is saved on a persistent location but the stack is not yet deployed it can break the node on a reboot e.g.

Also in hindsight of #15 we should think of how to manage this file in a cluster environment respectively on a bare-metal node running docker, podman.

**Comment by RenaudWasTaken** [comment]
> On OS's that have read-only file-systems not every location is writable.

Currently I'm thinking of `/etc/cdi/*.json` we can also have alternate path, I'm happy to review and merge PRs for that!

**Comment by elezar** [comment]
@klihub does it make sense to also include `/run/cdi` at some point?

Alternatively we need to provide references to the documentation for each runtime on where these knobs can be tuned. (e.g. config files).
