### ISSUE TITLE
Bump clients to v0.7.1

### ISSUE THREAD

**Issue by elezar** [cncf-tags/container-device-interface#199]
The following clients need to be updated to use https://github.com/cncf-tags/container-device-interface/releases/tag/v0.7.1

Note the deprecated APIs.

- [x] podman (@elezar)
    * common: https://github.com/containers/common/pull/1944 
    * podman: https://github.com/containers/podman/pull/22280
- [x] docker (@elezar):
    * Daemon: https://github.com/moby/moby/pull/47706
    * CLI: 
- [x] containerd (@bart0sh)
    - [x] `main`: https://github.com/containerd/containerd/pull/10041
    - [x] `release-1.7`: https://github.com/containerd/containerd/pull/10077
- [x] crio (@klihub): 
    - [x] `release-1.30`:
    - [x] `main`:
- [ ] singularity (@elezar)
    * 
- [ ] ctr (@elezar)
- [ ] nerdctl (@elezar)
    - https://github.com/containerd/nerdctl/pull/2280 needs to be updated
- ~[ ] kubernetes (@bart0sh)~

**Comment by kannon92** [comment]
What is required for CRIO?

**Comment by elezar** [comment]
@kannon92 we need to bump the dependencies and (optionally) move from the deprecated APIs. The containerd PR should be similar enough to be used as a guideline.

**Comment by kannon92** [comment]
I’ll see about doing it next week and I’ll cherry pick it to 1.30.

we are in the process of bumping a lot of dependencies right now with recent podman release.

**Comment by kannon92** [comment]
@klihub got to it already.

https://github.com/cri-o/cri-o/pull/7971

**Comment by kannon92** [comment]
How important is this for 1.30?

There is a very unlikely chance this will go into k8s 1.30.

CRI-O 1.30 branch aims to be 1on1 with k8s 1.30.

**Comment by bart0sh** [comment]
@kannon92 I don't think it's important as most of changed functionality makes sense only for runtimes.

**Comment by kannon92** [comment]
I did a quick search into kubernetes but didn't see that cdi is a dependency.

**Comment by elezar** [comment]
Kubernetes doesn't depend on the spec at all. It should only be forwarding the cdi device names as opaque strings. There is some logic around constructing the container annotations (if required) that may be shareable, but I don't believe we pull anything in for that. There were concerns about dependencies at some point and the relevant logic was duplicated instead.

**Comment by bart0sh** [comment]
It will depend on CDI spec soon. It's in my short term TODO list.

So far there are two places in the k/k code that would benefit from it:
- [this file](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/dra/test-driver/app/cdi.go) should be removed. and [this code](https://github.com/kubernetes/kubernetes/blob/master/test/e2e/dra/test-driver/app/kubeletplugin.go#L222-L235) should use imported [CDI spec](https://github.com/cncf-tags/container-device-interface/blob/main/specs-go/config.go) 
- [this code](https://github.com/kubernetes/kubernetes/blob/master/test/images/sample-device-plugin/sampledeviceplugin.go#L233-L248) should also use imported [CDI spec](https://github.com/cncf-tags/container-device-interface/blob/main/specs-go/config.go)

**Comment by klihub** [comment]
> @klihub @elezar thank you for your patience on the crio work. We had some long lasting bugs around our CI images. this actually helped get a PR I had sitting for a few months also so it is greatly apprechiated!

Thank for all your help with this, too !

**Comment by kannon92** [comment]
@bart0sh (bumping to keep this open) can you update this ticket with your k8s PR?

**Comment by elezar** [comment]
@kannon92 I think k8s would want to consume the v0.8.0 package / spec since this removes the dependency on the OCI runtime specification.

**Comment by kannon92** [comment]
Should we remove the call out for kubernetes then?

**Comment by bart0sh** [comment]
@kannon92 
> Should we remove the call out for kubernetes then?

I think it makes sense to remove. If https://github.com/kubernetes/kubernetes/pull/126435 is approved, the only copy of the  CDI structures is in the e2e tests: https://github.com/kubernetes/kubernetes/blob/master/test/e2e/dra/test-driver/app/cdi.go
This can be replaced with the specs-go import at some point, but it's not that urgent.
