### ISSUE TITLE
USB and other devices

### ISSUE THREAD

**Issue by beriberikix** [cncf-tags/container-device-interface#205]
I work in the world of embedded devices and this specification caught my eye! As a general question, how is a device defined? Graphics cards are mentioned throughout the documentation but would USB devices be in scope, as well as other common devices like Serial or Bluetooth (via HCI UART, for example.)

There are long-standing issues when it comes to interfacing with USB devices on [macOS](https://github.com/docker/for-mac/issues/900) & [Windows](https://github.com/docker/for-win/issues/1018) and I'm wondering if CDI could be a path to solve them.

Thanks!

**Comment by kad** [comment]
Everything that represented as POSIX device node will be ok for representing in CDI spec. 

```
~> ls -l /dev/hidraw*
crw------- 1 root root 245, 0 Mar 23 10:13 /dev/hidraw0
crw------- 1 root root 245, 1 Mar 23 10:13 /dev/hidraw1
~> ls -l /dev/bus/usb/00*
/dev/bus/usb/001:
total 0
crw-rw-r-- 1 root root 189, 0 Mar 23 10:13 001
crw-rw-r-- 1 root root 189, 1 Mar 23 10:13 002
crw-rw-r-- 1 root root 189, 2 Mar 23 10:13 003

```

For Windows, we don't have consistent story yet in CDI.
