### ISSUE TITLE
Support for specifying CDI devices through an API?

### ISSUE THREAD

**Issue by suptejas** [cncf-tags/container-device-interface#216]
> - Fully qualified device name should be passed to the runtime either using
  command line parameters for podman or using container annotations for CRI-O
  and containerd

What about users who'd like to use the API and CDI? Are you aware if this is supported via the Podman API?

Thanks a lot!

**Comment by elezar** [comment]
@suptejas I am not sure whether podman supports this. If I recall correctly, there was some work done to extend the functionality beyond the existing CLI-based support.

I would ask this question in a podman issue.
