### ISSUE TITLE
Add labels / annotations to devices, mounts, hooks and environments

### ISSUE THREAD

**Issue by elezar** [cncf-tags/container-device-interface#30]
It may be useful to add labels to devices, mounts, hooks, and environments defined in the CDI spec. This would allow for available devices or mounts (for example) to be filtered after the fact.

In the case of NVIDIA GPUs, for example we currently mount libraries from the host based on the value of various environment variables in the container spec.

**Comment by elezar** [comment]
As discussed in the meeting today, it may be possible to use something like the `when` statement for OCI hooks to conditionally included entities for injection into the spec. I will come up with more concrete examples of use cases with desired behaviour to drive this forward.

**Comment by zvonkok** [comment]
I am mostly interested in adding annotations, like in the OCI runtime spec: 

* **annotations** (map, OPTIONAL) contains the list of annotations associated with the device. If no annotations were provided then this property MAY either be absent or an empty map.
```
{
    "cdiVersion": "0.2.0",
    "annotations": {
        "myKey": "myValue"
    }
   ... 
}
```

In some cases, I need to provide additional meta-information that is needed for other entities like a hypervisor/operator/...  and not really related to the runtime using the device. 

One could misuse the ENV vars but this is kinda ugly.

**Comment by elezar** [comment]
@zvonkok would it make sense to add `annotations` as a top-level struct to mirror what is in the OCI runtime spec? Or do you specifically want them at a per-device level? (note that the association with a specific device in the annotations could be encoded as part of the `key`).

**Comment by zvonkok** [comment]
Per device level, because this meta information is only valid for a single device. But it could be also valuable to have top-level annotations.

**Comment by zvonkok** [comment]
I think encoding the device as part of the key will make parsing and updating "hard".
