### ISSUE TITLE
Support spec upgrades on read

### ISSUE THREAD

**Issue by elezar** [cncf-tags/container-device-interface#60]
When making changes to the spec:
* we will support the loading of old versions using the API
* we will only support writing the current spec version through the API

See also: https://github.com/containerd/containerd/pull/6654#discussion_r823950920

**Comment by pohly** [comment]
I have a related question (may or may not be worth a separate issue): when creating a spec, what version should be set in the Spec.Version field?

If only "writing the current spec version through the API" is supported, can that field be left blank and the lib will fill it in, or perhaps a constant can define the version string that a user of the code is supposed to use?

**Comment by klihub** [comment]
> I have a related question (may or may not be worth a separate issue): when creating a spec, what version should be set in the Spec.Version field?
> 
> If only "writing the current spec version through the API" is supported, can that field be left blank and the lib will fill it in, or perhaps a constant can define the version string that a user of the code is supposed to use?

I think normally that should be `container-orchestrated-devices/specs[-go].CurrentVersion`, IOW the `Spec version` of the `cdi` package you are compiling against.
