### ISSUE TITLE
Add "Getting Started" guide to README

### ISSUE THREAD

**Issue by elezar** [cncf-tags/container-device-interface#75]
We should have an end-to-end example that shows the use of CDI. 

This should:
* Use a vendor-agnostic spec (see https://github.com/container-orchestrated-devices/container-device-interface/pull/67#issuecomment-1183083813)
* Use `podman`
* Show the commands required and the expected output

We can also add links to vendor-specific examples once these are ready.

**Comment by en4bz** [comment]
The docs for containerd still do not seem to be correct. This was not resolve https://github.com/container-orchestrated-devices/container-device-interface/pull/67#issuecomment-1117008704

**Comment by en4bz** [comment]
As far as I can tell `ctr run` will not work without this PR: https://github.com/containerd/containerd/pull/7399

I assume similar changes would also need to be made for docker.

**Comment by elezar** [comment]
> As far as I can tell `ctr run` will not work without this PR: [containerd/containerd#7399](https://github.com/containerd/containerd/pull/7399)
> 
> I assume similar changes would also need to be made for docker.

The only CLI tool that currently has support for CDI devices is `podman` which allows fully-qualified CDI device names to be provided in the `--device` argument. This would have to be implemented in other CLIs including docker and ctr.
