### ISSUE TITLE
Does docker support CDI?

### ISSUE THREAD

**Issue by yeahdongcn** [cncf-tags/container-device-interface#84]
I noticed `docker` is mentioned in the `Examples` section, just wondering whether docker supports CDI, and are there any extra configurations on how to set up `docker`?

> ```bash
> # CLI examples below
> 
> # Verbose
> $ docker/podman run --device vendor.com/device=myDevice --device vendor.com/device=myDevice2 ...
> 
> # Less verbose, through infering the vendor from the device name
> $ docker/podman run --device myDevice ...
> 
> # Special case
> $ docker/podman run --device vendor.com/device=all ...
> ```

**Comment by elezar** [comment]
@yeahdongcn docker does not currently support CDI. This is something that we have been discussing, but have not had the opportunity to look at it yet.

Here we see a similar approach to `podman` being followed where the `--device` flag is extended to check for fully-qualified CDI device names and the apropriate modifications made to the OCI spec. Note that this would also have to disable the `--gpus` flag (and possibly even mark this as deprecated).

Note that there are other docker use cases that are not covered by this, including `docker-compose` and one would have to work with the community to add CDI support there too.

**Comment by elezar** [comment]
We have created https://github.com/docker/cli/issues/3864 to track the work required on the docker front. Thre is not yet a timeline on this.

**Comment by elezar** [comment]
We have created https://github.com/moby/moby/pull/45134 and https://github.com/docker/cli/pull/4084 to add CDI support to `moby` and the Docker CLI.

**Comment by bart0sh** [comment]
@elezar both above mentioned PRs have been merged. Should we close this issue?
