### ISSUE TITLE
reconsider dependencies

### ISSUE THREAD

**Issue by pohly** [cncf-tags/container-device-interface#97]
Using this repository is not possible in Kubernetes because even just having problematic dependencies in the dependency graph is flagged as a problem, even if no code from those dependencies is needed in Kubernetes:
- https://github.com/kubernetes/kubernetes/pull/111023#issuecomment-1309058680
- https://github.com/kubernetes/kubernetes/pull/111023#issuecomment-1309273728

The solution I came up with for now consists of copying some code from this repo into Kubernetes:
- test/e2e/dra/test-driver/app/cdi.go (simplified struct defs)
- pkg/kubelet/cm/dra/cdi.go (helper functions for working with CDI strings).

Long term it would be good to have that code in a Go module with no problematic dependencies.
This can be done by splitting this repo or with multiple Go modules in the existing one.

**Comment by klihub** [comment]
https://github.com/kubernetes/kubernetes/pull/111023#issuecomment-1309058680

**Comment by klihub** [comment]
Filed [this issue](https://github.com/opencontainers/runtime-tools/issues/758) for runtime-tools, describing the problem and telling that we're (as in the folks from Intel and Nvidia working on DRA and CDI) ready to do the actual heavy lifting as long as we can agree with the runtime-tools maintainers about what is acceptable lifting.
